CREATE TABLE IF NOT EXISTS "device_tokens" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "token" text NOT NULL,
  "platform" varchar(10) NOT NULL,
  "device_id" varchar(255),
  "last_seen" timestamp DEFAULT now() NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_device_tokens_user" ON "device_tokens" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "device_tokens_token_unique" ON "device_tokens" ("token");
