-- Console Runs table: tracks IDE code execution runs (Run button)
-- Fixes: column "logs" of relation "console_runs" does not exist

-- Drop the stale table if it exists without the logs column
DROP TABLE IF EXISTS "console_runs" CASCADE;

-- Create the table with all required columns
CREATE TABLE IF NOT EXISTS "console_runs" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "project_id" integer NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "execution_id" varchar(128) NOT NULL,
  "language" varchar(64),
  "status" varchar(32) NOT NULL DEFAULT 'running',
  "exit_code" integer,
  "logs" text,
  "error" text,
  "execution_time" integer,
  "started_at" timestamp NOT NULL DEFAULT now(),
  "completed_at" timestamp
);

CREATE INDEX IF NOT EXISTS "console_runs_project_idx" ON "console_runs" ("project_id");
CREATE INDEX IF NOT EXISTS "console_runs_user_idx" ON "console_runs" ("user_id");
CREATE INDEX IF NOT EXISTS "console_runs_execution_id_idx" ON "console_runs" ("execution_id");
CREATE INDEX IF NOT EXISTS "console_runs_started_at_idx" ON "console_runs" ("started_at");
