import { db } from './db';
import { templates } from '@shared/schema';

const REPLIT_TEMPLATES = [
  // Web Development
  {
    slug: 'nextjs-starter',
    name: 'Next.js 14 Starter',
    description: 'Full-stack Next.js app with TypeScript, Tailwind CSS, and App Router',
    icon: 'Globe',
    category: 'web',
    tags: ['nextjs', 'react', 'typescript', 'tailwind', 'fullstack'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Next.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['App Router', 'TypeScript', 'Tailwind CSS', 'ESLint', 'SEO optimized'],
    files: {
      'package.json': JSON.stringify({
        name: 'nextjs-starter',
        dependencies: {
          'next': 'latest',
          'react': 'latest',
          'react-dom': 'latest'
        },
        devDependencies: {
          '@types/node': 'latest',
          '@types/react': 'latest',
          'typescript': 'latest',
          'tailwindcss': 'latest'
        }
      }),
      'app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js!</h1>
    </main>
  );
}`
    },
    dependencies: { 'next': '^14.0.0', 'react': '^18.0.0' },
    uses: 5420,
    stars: 342,
    forks: 89,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'react-vite',
    name: 'React + Vite',
    description: 'Lightning-fast React development with Vite, TypeScript, and modern tooling',
    icon: 'Zap',
    category: 'web',
    tags: ['react', 'vite', 'typescript', 'fast-refresh'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'React',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Hot Module Replacement', 'TypeScript', 'Fast builds', 'Modern tooling'],
    files: {},
    dependencies: { 'react': '^18.0.0', 'vite': '^5.0.0' },
    uses: 3210,
    stars: 256,
    forks: 67,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'vue3-composition',
    name: 'Vue 3 + Composition API',
    description: 'Modern Vue 3 app with Composition API, TypeScript, and Pinia',
    icon: 'Code',
    category: 'web',
    tags: ['vue', 'composition-api', 'typescript', 'pinia'],
    authorName: 'Vue Masters',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Vue.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Composition API', 'TypeScript', 'Pinia store', 'Vue Router'],
    files: {},
    dependencies: { 'vue': '^3.0.0', '@vue/composition-api': 'latest' },
    uses: 2150,
    stars: 178,
    forks: 45,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'angular-universal',
    name: 'Angular Universal SSR',
    description: 'Server-side rendered Angular app with Universal and TypeScript',
    icon: 'Shield',
    category: 'web',
    tags: ['angular', 'ssr', 'typescript', 'universal'],
    authorName: 'Angular Experts',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Angular',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Server-side rendering', 'TypeScript', 'Angular CLI', 'RxJS'],
    files: {},
    dependencies: { '@angular/core': '^17.0.0' },
    uses: 1890,
    stars: 145,
    forks: 38,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'svelte-kit',
    name: 'SvelteKit Full-Stack',
    description: 'Full-stack SvelteKit app with TypeScript and Tailwind CSS',
    icon: 'Layers',
    category: 'web',
    tags: ['svelte', 'sveltekit', 'typescript', 'fullstack'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'SvelteKit',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['SvelteKit', 'TypeScript', 'Tailwind CSS', 'Full-stack'],
    files: {},
    dependencies: { '@sveltejs/kit': '^2.0.0' },
    uses: 1670,
    stars: 123,
    forks: 31,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Backend/API
  {
    slug: 'express-typescript-api',
    name: 'Express.js TypeScript API',
    description: 'Production-ready REST API with Express, TypeScript, and JWT auth',
    icon: 'Server',
    category: 'api',
    tags: ['express', 'typescript', 'api', 'jwt', 'rest'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Express.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['TypeScript', 'JWT Authentication', 'MongoDB', 'Input validation'],
    files: {},
    dependencies: { 'express': '^4.0.0', 'typescript': '^5.0.0' },
    uses: 4320,
    stars: 289,
    forks: 76,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'fastapi-python',
    name: 'FastAPI Python Backend',
    description: 'High-performance Python API with FastAPI, async support, and auto-docs',
    icon: 'Zap',
    category: 'api',
    tags: ['python', 'fastapi', 'async', 'api', 'swagger'],
    authorName: 'Python Pro',
    authorVerified: true,
    language: 'Python',
    framework: 'FastAPI',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Async/await', 'Auto documentation', 'Type hints', 'Fast performance'],
    files: {},
    dependencies: {},
    uses: 3890,
    stars: 267,
    forks: 69,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'django-rest-api',
    name: 'Django REST Framework',
    description: 'Full-featured Django REST API with authentication and PostgreSQL',
    icon: 'Database',
    category: 'api',
    tags: ['python', 'django', 'rest', 'postgresql', 'api'],
    authorName: 'Django Masters',
    authorVerified: true,
    language: 'Python',
    framework: 'Django',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Django REST Framework', 'PostgreSQL', 'JWT Auth', 'Admin panel'],
    files: {},
    dependencies: {},
    uses: 2780,
    stars: 198,
    forks: 52,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'nestjs-microservices',
    name: 'NestJS Microservices',
    description: 'Scalable microservices architecture with NestJS and TypeScript',
    icon: 'GitBranch',
    category: 'api',
    tags: ['nestjs', 'microservices', 'typescript', 'scalable'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'NestJS',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Microservices', 'TypeScript', 'Message queues', 'Docker ready'],
    files: {},
    dependencies: { '@nestjs/core': '^10.0.0' },
    uses: 2340,
    stars: 176,
    forks: 43,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'graphql-apollo',
    name: 'GraphQL Apollo Server',
    description: 'GraphQL API with Apollo Server, TypeScript, and subscriptions',
    icon: 'GitGraph',
    category: 'api',
    tags: ['graphql', 'apollo', 'typescript', 'subscriptions'],
    authorName: 'GraphQL Experts',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Apollo',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['GraphQL', 'Subscriptions', 'TypeScript', 'Apollo Server'],
    files: {},
    dependencies: { 'apollo-server': '^3.0.0' },
    uses: 1980,
    stars: 143,
    forks: 36,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Mobile
  {
    slug: 'react-native-expo',
    name: 'React Native + Expo',
    description: 'Cross-platform mobile app with React Native and Expo SDK',
    icon: 'Smartphone',
    category: 'mobile',
    tags: ['react-native', 'expo', 'mobile', 'ios', 'android'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'React Native',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Expo SDK', 'Cross-platform', 'Hot reload', 'Native features'],
    files: {},
    dependencies: { 'expo': '^49.0.0', 'react-native': '^0.72.0' },
    uses: 3560,
    stars: 234,
    forks: 61,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'flutter-material',
    name: 'Flutter Material App',
    description: 'Beautiful Flutter app with Material Design and state management',
    icon: 'Palette',
    category: 'mobile',
    tags: ['flutter', 'dart', 'material-design', 'mobile'],
    authorName: 'Flutter Pro',
    authorVerified: true,
    language: 'Dart',
    framework: 'Flutter',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Material Design', 'State management', 'Hot reload', 'Cross-platform'],
    files: {},
    dependencies: {},
    uses: 2890,
    stars: 189,
    forks: 49,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'ionic-angular',
    name: 'Ionic Angular App',
    description: 'Hybrid mobile app with Ionic, Angular, and Capacitor',
    icon: 'Radio',
    category: 'mobile',
    tags: ['ionic', 'angular', 'capacitor', 'hybrid', 'mobile'],
    authorName: 'Ionic Masters',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Ionic',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Ionic components', 'Angular', 'Capacitor', 'PWA ready'],
    files: {},
    dependencies: { '@ionic/angular': '^7.0.0' },
    uses: 1670,
    stars: 112,
    forks: 28,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Games
  {
    slug: 'phaser3-platformer',
    name: 'Phaser 3 Platformer',
    description: '2D platformer game with Phaser 3, physics, and level editor',
    icon: 'Gamepad2',
    category: 'game',
    tags: ['phaser', 'game', 'javascript', 'platformer', '2d'],
    authorName: 'Game Dev Pro',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Phaser',
    difficulty: 'intermediate' as const,
    estimatedTime: '4 minutes',
    features: ['Physics engine', 'Level editor', 'Sprite animations', 'Sound effects'],
    files: {},
    dependencies: { 'phaser': '^3.0.0' },
    uses: 2340,
    stars: 167,
    forks: 43,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'unity-webgl',
    name: 'Unity WebGL Starter',
    description: '3D Unity game exported to WebGL for browser play',
    icon: 'Gamepad',
    category: 'game',
    tags: ['unity', 'webgl', '3d', 'game', 'c-sharp'],
    authorName: 'Unity Masters',
    authorVerified: true,
    language: 'C#',
    framework: 'Unity',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['3D graphics', 'WebGL export', 'Physics', 'Multiplayer ready'],
    files: {},
    dependencies: {},
    uses: 1890,
    stars: 134,
    forks: 35,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'kaboomjs-arcade',
    name: 'Kaboom.js Arcade Game',
    description: 'Retro arcade game with Kaboom.js game engine',
    icon: 'Zap',
    category: 'game',
    tags: ['kaboom', 'game', 'javascript', 'arcade', 'retro'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Kaboom.js',
    difficulty: 'beginner' as const,
    estimatedTime: '2 minutes',
    features: ['Simple API', 'Built-in physics', 'Asset loading', 'Scene management'],
    files: {},
    dependencies: { 'kaboom': 'latest' },
    uses: 1560,
    stars: 98,
    forks: 24,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Data Science & ML
  {
    slug: 'jupyter-datascience',
    name: 'Jupyter Data Science',
    description: 'Complete data science environment with Jupyter, NumPy, Pandas, and Matplotlib',
    icon: 'BarChart',
    category: 'data',
    tags: ['python', 'jupyter', 'pandas', 'numpy', 'data-science'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: 'Jupyter',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Jupyter notebook', 'Data visualization', 'Statistical analysis', 'Machine learning'],
    files: {},
    dependencies: {},
    uses: 4560,
    stars: 312,
    forks: 82,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'tensorflow-ml',
    name: 'TensorFlow ML Starter',
    description: 'Machine learning project with TensorFlow, Keras, and model training',
    icon: 'Brain',
    category: 'data',
    tags: ['python', 'tensorflow', 'machine-learning', 'keras', 'ai'],
    authorName: 'ML Experts',
    authorVerified: true,
    language: 'Python',
    framework: 'TensorFlow',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Neural networks', 'Model training', 'Data preprocessing', 'GPU support'],
    files: {},
    dependencies: {},
    uses: 3210,
    stars: 234,
    forks: 61,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'pytorch-computer-vision',
    name: 'PyTorch Computer Vision',
    description: 'Computer vision project with PyTorch, image classification, and CNNs',
    icon: 'Eye',
    category: 'data',
    tags: ['python', 'pytorch', 'computer-vision', 'cnn', 'ai'],
    authorName: 'Vision AI',
    authorVerified: true,
    language: 'Python',
    framework: 'PyTorch',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['CNN models', 'Image classification', 'Transfer learning', 'GPU acceleration'],
    files: {},
    dependencies: {},
    uses: 2670,
    stars: 189,
    forks: 49,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Bots & Automation
  {
    slug: 'discord-bot-js',
    name: 'Discord Bot JavaScript',
    description: 'Feature-rich Discord bot with slash commands and database',
    icon: 'Bot',
    category: 'bot',
    tags: ['discord', 'bot', 'javascript', 'discord.js'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Discord.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Slash commands', 'Database integration', 'Music player', 'Moderation tools'],
    files: {},
    dependencies: { 'discord.js': '^14.0.0' },
    uses: 3890,
    stars: 267,
    forks: 69,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'telegram-bot-python',
    name: 'Telegram Bot Python',
    description: 'Telegram bot with inline keyboards, webhooks, and payments',
    icon: 'MessageCircle',
    category: 'bot',
    tags: ['telegram', 'bot', 'python', 'automation'],
    authorName: 'Bot Masters',
    authorVerified: true,
    language: 'Python',
    framework: 'python-telegram-bot',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Inline keyboards', 'Webhooks', 'Payment integration', 'Multi-language'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 167,
    forks: 43,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'slack-bot-node',
    name: 'Slack Bot Node.js',
    description: 'Slack workspace bot with interactive messages and workflows',
    icon: 'Hash',
    category: 'bot',
    tags: ['slack', 'bot', 'nodejs', 'automation', 'workspace'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Bolt',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Interactive messages', 'Workflows', 'Slash commands', 'Event handling'],
    files: {},
    dependencies: { '@slack/bolt': '^3.0.0' },
    uses: 1890,
    stars: 134,
    forks: 35,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Blockchain & Web3
  {
    slug: 'ethereum-dapp',
    name: 'Ethereum DApp Starter',
    description: 'Decentralized app with Solidity smart contracts and React frontend',
    icon: 'Coins',
    category: 'web3',
    tags: ['ethereum', 'solidity', 'web3', 'blockchain', 'dapp'],
    authorName: 'Web3 Builders',
    authorVerified: true,
    language: 'Solidity',
    framework: 'Hardhat',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['Smart contracts', 'Web3 integration', 'MetaMask', 'Testing suite'],
    files: {},
    dependencies: {},
    uses: 2120,
    stars: 156,
    forks: 40,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'nft-marketplace',
    name: 'NFT Marketplace',
    description: 'Full-stack NFT marketplace with minting, buying, and selling',
    icon: 'Image',
    category: 'web3',
    tags: ['nft', 'ethereum', 'marketplace', 'web3', 'ipfs'],
    authorName: 'NFT Pro',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Next.js',
    difficulty: 'advanced' as const,
    estimatedTime: '6 minutes',
    features: ['NFT minting', 'IPFS storage', 'Marketplace', 'Wallet integration'],
    files: {},
    dependencies: {},
    uses: 1780,
    stars: 123,
    forks: 31,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // DevOps & Tools
  {
    slug: 'github-actions-ci',
    name: 'GitHub Actions CI/CD',
    description: 'Complete CI/CD pipeline with GitHub Actions, testing, and deployment',
    icon: 'GitPullRequest',
    category: 'tools',
    tags: ['github-actions', 'ci-cd', 'devops', 'automation'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'YAML',
    framework: 'GitHub Actions',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Automated testing', 'Multi-environment deploy', 'Docker builds', 'Secrets management'],
    files: {},
    dependencies: {},
    uses: 2890,
    stars: 198,
    forks: 52,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'docker-compose-stack',
    name: 'Docker Compose Stack',
    description: 'Multi-container Docker application with database, cache, and monitoring',
    icon: 'Container',
    category: 'tools',
    tags: ['docker', 'docker-compose', 'devops', 'containers'],
    authorName: 'DevOps Masters',
    authorVerified: true,
    language: 'YAML',
    framework: 'Docker',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Multi-container', 'Database setup', 'Redis cache', 'Monitoring stack'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 167,
    forks: 43,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Starter Templates
  {
    slug: 'html-css-js',
    name: 'HTML/CSS/JS Starter',
    description: 'Simple web page with HTML5, CSS3, and vanilla JavaScript',
    icon: 'Code',
    category: 'starter',
    tags: ['html', 'css', 'javascript', 'beginner', 'web'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'HTML',
    framework: undefined,
    difficulty: 'beginner' as const,
    estimatedTime: '30 seconds',
    features: ['Responsive design', 'Modern CSS', 'JavaScript interactivity', 'SEO friendly'],
    files: {},
    dependencies: {},
    uses: 8920,
    stars: 456,
    forks: 123,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'python-script',
    name: 'Python Script Starter',
    description: 'Python script template with common utilities and best practices',
    icon: 'FileCode',
    category: 'starter',
    tags: ['python', 'script', 'automation', 'beginner'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: undefined,
    difficulty: 'beginner' as const,
    estimatedTime: '30 seconds',
    features: ['Argument parsing', 'Logging setup', 'Error handling', 'Type hints'],
    files: {},
    dependencies: {},
    uses: 6780,
    stars: 342,
    forks: 89,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'nodejs-cli',
    name: 'Node.js CLI Tool',
    description: 'Command-line tool with Node.js, Commander.js, and chalk',
    icon: 'Terminal',
    category: 'starter',
    tags: ['nodejs', 'cli', 'terminal', 'tool'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: undefined,
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Command parsing', 'Colorful output', 'Progress bars', 'Config files'],
    files: {},
    dependencies: { 'commander': '^11.0.0', 'chalk': '^5.0.0' },
    uses: 4320,
    stars: 234,
    forks: 61,
    isFeatured: false,
    isOfficial: true,
    published: true
  }
];

async function seedTemplates() {
  console.log('🌱 Seeding templates...');
  
  try {
    // Clear existing templates (optional)
    await db.delete(templates);
    console.log('✅ Cleared existing templates');
    
    // Insert all templates
    for (const template of REPLIT_TEMPLATES) {
      await db.insert(templates).values(template);
      console.log(`✅ Added template: ${template.name}`);
    }
    
    console.log(`✅ Successfully seeded ${REPLIT_TEMPLATES.length} templates!`);
  } catch (error) {
    console.error('❌ Error seeding templates:', error);
    throw error;
  }
}

// Run the seed function
seedTemplates()
  .then(() => {
    console.log('✅ Template seeding completed!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Template seeding failed:', error);
    process.exit(1);
  });