# E-Code Platform Main Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-code-typescript
  namespace: e-code-platform
  labels:
    app: e-code
    component: typescript-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-code
      component: typescript-core
  template:
    metadata:
      labels:
        app: e-code
        component: typescript-core
    spec:
      containers:
      - name: typescript-core
        image: gcr.io/PROJECT_ID/e-code-platform:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: SERVICE_TYPE
          value: "typescript"
        - name: PORT
          value: "5000"
        envFrom:
        - configMapRef:
            name: e-code-config
        - secretRef:
            name: e-code-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-code-go-runtime
  namespace: e-code-platform
  labels:
    app: e-code
    component: go-runtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-code
      component: go-runtime
  template:
    metadata:
      labels:
        app: e-code
        component: go-runtime
    spec:
      containers:
      - name: go-runtime
        image: gcr.io/PROJECT_ID/e-code-go-runtime:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVICE_TYPE
          value: "go-runtime"
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: e-code-config
        - secretRef:
            name: e-code-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-code-python-ml
  namespace: e-code-platform
  labels:
    app: e-code
    component: python-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-code
      component: python-ml
  template:
    metadata:
      labels:
        app: e-code
        component: python-ml
    spec:
      containers:
      - name: python-ml
        image: gcr.io/PROJECT_ID/e-code-python-ml:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SERVICE_TYPE
          value: "python-ml"
        - name: PORT
          value: "8081"
        envFrom:
        - configMapRef:
            name: e-code-config
        - secretRef:
            name: e-code-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-code-mcp-server
  namespace: e-code-platform
  labels:
    app: e-code
    component: mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-code
      component: mcp-server
  template:
    metadata:
      labels:
        app: e-code
        component: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: gcr.io/PROJECT_ID/e-code-mcp:latest
        ports:
        - containerPort: 3200
          name: http
        env:
        - name: SERVICE_TYPE
          value: "mcp-server"
        - name: PORT
          value: "3200"
        envFrom:
        - configMapRef:
            name: e-code-config
        - secretRef:
            name: e-code-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3200
          initialDelaySeconds: 30
          periodSeconds: 10