# Horizontal Pod Autoscaler for E-Code Platform
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: typescript-hpa
  namespace: e-code-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e-code-typescript
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-runtime-hpa
  namespace: e-code-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e-code-go-runtime
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-ml-hpa
  namespace: e-code-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e-code-python-ml
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85