# Ingress Controller for E-Code Platform
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-code-ingress
  namespace: e-code-platform
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/websocket-services: "typescript-service"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
spec:
  tls:
  - hosts:
    - ecode.cloud
    - "*.ecode.cloud"
    secretName: e-code-tls
  rules:
  - host: ecode.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: typescript-service
            port:
              number: 5000
      - path: /api/go
        pathType: Prefix
        backend:
          service:
            name: go-runtime-service
            port:
              number: 8080
      - path: /api/ml
        pathType: Prefix
        backend:
          service:
            name: python-ml-service
            port:
              number: 8081
      - path: /mcp
        pathType: Prefix
        backend:
          service:
            name: mcp-service
            port:
              number: 3200
  - host: "*.ecode.cloud"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: typescript-service
            port:
              number: 5000